### ISSUE TITLE
Telegram Missing

### ISSUE THREAD

**Issue by cutzenfriend** [ezkrg/docker-bitlbee-libpurple#10]
Somehow the Telegram Plugin is missing...

![plugins-bitlbee](https://user-images.githubusercontent.com/1510611/61589943-7c087180-abb1-11e9-9fe4-38480ffda7fe.png)

**Comment by ezkrg** [comment]
I have upgraded to alpine 3.10 and bitlbee 3.6 and now the telegram plugin is working again.

Please test it and if everything goes well close the issue.

**Comment by cutzenfriend** [comment]
Working fine! Thanks! :)
