### ISSUE TITLE
Whatsapp

### ISSUE THREAD

**Issue by jkaberg** [ezkrg/docker-bitlbee-libpurple#18]
Would you mind adding [purple-gowhatsapp](https://github.com/hoehermann/purple-gowhatsapp) aswell?

**Comment by ezkrg** [comment]
The following error raised when try to load the plugin. It's a go vs musl libc vs glibc problem, it will not work with alpine now. I'm looking for a possible solution.

`(17:13:04) plugins: probing /usr/lib/purple-2/libgowhatsapp.so`
`(17:13:04) plugins: /usr/lib/purple-2/libgowhatsapp.so is not loadable: Error relocating /usr/lib/purple-2/libgowhatsapp.so: _cgoexp_0e44ac79674d_gowhatsapp_go_close: initial-exec TLS resolves to dynamic definition in /usr/lib/purple-2/libgowhatsapp.so`

**Comment by ezkrg** [comment]
The situation is the same. I think only a glibc based base image will solve this issue. I'm working on debian based bitlbee image.

**Comment by ezkrg** [comment]
You can use it with Dockerfile.debian or any tag begins with debian from docker hub.
