### ISSUE TITLE
Slack settings and commands not working

### ISSUE THREAD

**Issue by vnckppl** [ezkrg/docker-bitlbee-libpurple#21]
I am not sure if I am doing something wrong or if the slack plugin is different from this one: https://github.com/dylex/slack-libpurple , so please let me know if the features I am looking for do not apply to the slack plugin here.

I am looking to set the variables `open_chat`, `connect_history`, and `thread_history`, but I can't find them. `set` or `acc <some_account> set` do not show these variables.

Also, the command `\history` does not work for me. It gives the error message `history: Unknown command`.

Any pointers are appreciated.

**Comment by ezkrg** [comment]
It does not work for me either.

I've tried with irssi script dispatch that send unknown commands to the server, the error message disappear but nothing happend.

I think it's a bitlbee + slack-libpurple combo-miss-behaviour. Maybe you can issue that at the plugin repository.

**Comment by vnckppl** [comment]
I was able to resolve this by changing `ARG SLACK_VERSION=2e9fa02` to `ARG SLACK_VERSION=e0c73ae` and then rebuilding the Docker.

**Comment by ezkrg** [comment]
thanks for info.
