### ISSUE TITLE
Matrix missing

### ISSUE THREAD

**Issue by S73ph4n** [ezkrg/docker-bitlbee-libpurple#24]
Hello,
It looks like the matrix plugin is missing :

![IMG_20210915_104430.jpg](https://user-images.githubusercontent.com/1709064/133401465-0f1e8d4c-dec7-452c-9c02-e85090631b88.jpg)

(PS : Thanks for the work you've done with this docker image, it really is super useful.)

**Comment by ezkrg** [comment]
are you using a tag from docker hub or build it for self?

**Comment by ezkrg** [comment]
it was a bad filename in copy stage, matrix plugin looking for libolm.so.3 not libolm.so. commit [25e7283](https://github.com/ezkrg/docker-bitlbee-libpurple/commit/25e728325c5ac5ab34ca18e120b2c15458d437be) fixed it.
