### ISSUE TITLE
Migrate to tdlib-purple

### ISSUE THREAD

**Issue by mooomooo** [ezkrg/docker-bitlbee-libpurple#28]
According to the [telegram-purple](https://github.com/majn/telegram-purple) repo: 
> This project is effectively *abandoned*.

It's recommended to switch to [tdlib-purple](https://github.com/ars3niy/tdlib-purple/) instead.

**Comment by ezkrg** [comment]
migrated: [b777103](https://github.com/ezkrg/docker-bitlbee-libpurple/commit/b77710328a2fc8808eed79109f702a3213b182dd).
