### ISSUE TITLE
Feature request: Spectrum.im support

### ISSUE THREAD

**Issue by mooomooo** [ezkrg/docker-bitlbee-libpurple#30]
I tried to get this working with the Spectrum.im XMPP transport, but I wasn't able to figure out how to wrangle all the bits.  It'd be great if we could use this same framework to set up a similar plug-and-play docker for libpurple to XMPP.

**Comment by ezkrg** [comment]
i'dont understand exactly what do you mean. If you want plain xmpp you can use bitlbees built-in xmpp (jabber), or if you mean [spectrum.im](https://spectrum.im) i think you can make a try with whatsapp-go in debian based image.

**Comment by ezkrg** [comment]
close because of inactivity. feel free to reopen.
