### ISSUE TITLE
Letsencypt certificate authority

### ISSUE THREAD

**Issue by mooomooo** [ezkrg/docker-bitlbee-libpurple#31]
Letsencrypt did something to their certificates earlier this year, and now bitlbee refuses to connect to letsencrypt signed servers (e.g. self-hosted rocketchat) -- the appropriate CA would need to be updated somehow.

**Comment by mooomooo** [comment]
This is very clearly a horrendous hack, but nuking the offending certificate from the official store (as suggested by https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/) does the trick.  I added the line:
```
RUN sed -e '/DST Root CA X3/,+19d' -i.backup /usr/share/purple/ca-certs/mozilla.pem
```
to the end of the Dockerfile which seems to work for now.

**Comment by ezkrg** [comment]
the latest image updated to alpine3.15 with newer packages. please make a try with it.

**Comment by ezkrg** [comment]
feel free reopen if the update not solve the problem.
