### ISSUE TITLE
Facebook User Agent is Wrong

### ISSUE THREAD

**Issue by warshell** [ezkrg/docker-bitlbee-libpurple#32]
Hello please can you try fix this, facebook dosent work
bitlbee/bitlbee-facebook#195
https://github.com/dequis/purple-facebook/search?q=FB_ORCA_AGENT

**Comment by ezkrg** [comment]
as i know it's not about the user agent. i've got the same error, and if i remember right, the solution was logging-in with a browser from same ip address where the bitlbee server running from.

**Comment by ezkrg** [comment]
i've tested it again and follow the steps in [bitlbee facebook howto](https://wiki.bitlbee.org/HowtoFacebookMQTT) works.

**Comment by warshell** [comment]
The problem was that i authenticated from the local pc and the bitlbee remote server. You need to authenticate directly from server.
