### ISSUE TITLE
Update purple-gowhatsapp dependency (to use purple-whatsmeow)

### ISSUE THREAD

**Issue by shanedabes** [ezkrg/docker-bitlbee-libpurple#33]
[purple-gowhatsapp](https://github.com/hoehermann/purple-gowhatsapp) has updated to use the whatsmeow library over go-whatsapp, this should fix a lot of the bugs and problems in the old implementation. Do you think you'd be able to build a new image with the new library included?

**Comment by ezkrg** [comment]
updated: [5bd5d19](https://github.com/ezkrg/docker-bitlbee-libpurple/commit/5bd5d19125cc1120b5bbd903446dd67e9dbaf5e6).
