### ISSUE TITLE
telegram-purple or tdlib-purple

### ISSUE THREAD

**Issue by warshell** [ezkrg/docker-bitlbee-libpurple#34]
Hello, do you using a https://github.com/majn/telegram-purple or a https://github.com/ars3niy/tdlib-purple/?
Thanks

**Comment by ezkrg** [comment]
you can check it [here](https://github.com/ezkrg/docker-bitlbee-libpurple/blob/043f87148259ddfc810b9f9dfb5be97026406369/Dockerfile#L115).

**Comment by mooomooo** [comment]
the README link still points to telegram-purple.
