### ISSUE TITLE
default ALPINE_VERSION not set

### ISSUE THREAD

**Issue by mooomooo** [ezkrg/docker-bitlbee-libpurple#35]
There's no default value for `ALPINE_VERSION` in the Dockerfile, so it seems to not build unless the argument is explicitly provided.  Perhaps a default needs to be set in the Dockerfile?  Or the README could get updated with an explicit build arg provided.  Also, should it get added to plugin_versions?

**Comment by ticklemynausea** [comment]
I have tried several combinations of `ALPINE_VERSION` and `BITLBEE_VERSION` and couldn't get it to work. Maybe you could provide documentation on what versions are supported?

**Comment by ezkrg** [comment]
Alpine versions can be found in .drone.yml file: 3.15 for amd64 only image and 3.12 for arm / amd64 image.
All other versions can be found in plugin_versions file.
